namespace SqlParser
{
    public enum TokenType
    {
        Id,
        LiteralString,
        LiteralInt,
        RwCreate,
        RwDrop,
        RwInsert,
        RwSelect,
        RwUpdate,
        RwDelete,
        RwInto,
        RwValues,
        RwFrom,
        RwSet,
        RwWhere,
        RwDatabase,
        RwAnd,
        RwOr,
        RwMb,
        RwGb,
        OpAll,
        OpEqual,
        OpNotEqual,
        OpGreaterThan,
        OpLessThan,
        OpGreaterThanOrEqual,
        OpLessThanOrEqual,
        ParenthesisOpen,
        ParenthesisClose,
        Comma,
        EndStatement,
        Eof
    }
}
